[build]
command = "npm run generate"
publish = "dist/"

[functions]
node_bundler = "esbuild"

# [[plugins]]
# package = "netlify-plugin-subfont"

[[plugins]]
package = "netlify-plugin-a11y"

  [plugins.inputs]
  
  ignoreDirectories = ['/admin']
  resultMode = "warn"

[[plugins]]
package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	providers = ["google", "bing"]