# TODO: edit site_url
site_url: https://northsideministries.netlify.app/
logo_url: https://northsideministries.netlify.app/icon.png
display_url: https://www.northsideministries.com/

# publish_mode: editorial_workflow
local_backend: true
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'site'
    label: 'Site settings'
    description: 'General site information.'
    files:
      - label: 'Info'
        name: 'info'
        file: 'assets/content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'blog'
    label: 'Blog'
    # identifier_field: name
    folder: 'assets/content/blog'
    create: true
    format: 'json'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
