# TODO: edit site_url
site_url: https://northsideministries.netlify.app/
logo_url: https://northsideministries.netlify.app/icon.png
display_url: https://www.northsideministries.com/

local_backend: true
# publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img
media_library:
  name: cloudinary
  config:
    cloud_name: northside-baptist-church
    api_key: 728192525896344
    default_transformations:
      - - fetch_format: auto
          crop: fill
          quality: 35
          width: 0.35

###############
# ALIASES     #
###############

ministry: &MINISTRY
  - { label: Ministry Name, name: name, widget: string, required: true }
  - { label: Description, name: description, widget: text, required: true }
  - label: 'Weekday'
    name: 'day'
    widget: 'select'
    options: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
    required: false
  - { label: Image, name: image, widget: image, required: true }
  - { label: Room, name: room, widget: string, required: false }
  - { label: Service, name: service, widget: string, required: false }
  - { label: Time, name: time, widget: string, required: false }
  - label: 'Link'
    name: 'link'
    required: false
    widget: 'object'
    hint: 'Add a link to another page'
    fields:
      - { label: Label, name: label, widget: string, required: false }
      - label: 'Link to Page'
        hint: 'Link to a page on the website'
        name: 'page_link'
        widget: 'select'
        options:
          - { label: 'About', value: '/about' }
          - { label: 'Beliefs', value: '/about/beliefs' }
          - { label: "Children's Ministries", value: '/ministries/childrens-ministries' }
          - { label: 'Contact', value: '/contact' }
          - { label: 'COVID-19', value: '/covid' }
          - { label: 'Events', value: '/events' }
          - { label: 'Give', value: '/give' }
          - { label: 'Home', value: '/' }
          - { label: 'Leadership', value: '/about/leadership' }
          - { label: 'Ministries', value: '/ministries' }
          - { label: 'Missions', value: '/ministries/missions' }
          - { label: 'Sunday School', value: '/ministries/sunday-school' }
          - { label: 'Watch', value: '/watch' }
          - { label: 'Youth Ministries', value: '/ministries/youth-ministries' }
        required: false
      - label: 'External Link'
        hint: 'Link to an external website or webpage'
        name: 'external_link'
        widget: 'string'
        required: false

###############
# END ALIASES #
###############

collections:
  - label: 'Site Settings'
    name: 'site'
    description: 'General site information.'
    files:
      - label: 'Site Information'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
      - label: 'Livestream and Social Media'
        name: services
        description: 'Links to livestream and social media services.'
        file: 'content/site/services.json'
        editor:
          preview: false
        fields:
          - { label: 'Facebook', name: facebook, widget: string, hint: 'Link to Facebook page' }
          - { label: 'YouTube', name: youtube, widget: string, hint: 'Link to YouTube channel' }
          - label: 'Sunday School Livestreams'
            summary: 'Zoom livestream link'
            name: 'livestream_list'
            minimize_collapsed: true
            widget: 'list'
            fields:
              - { label: Teacher, name: teacher, widget: string, required: true }
              - { label: Class, name: class, widget: string, required: true }
              - { label: Link, name: link, widget: string, required: true }
          - {
              label: 'Livestream Notification',
              name: livestream,
              widget: boolean,
              default: true,
              hint: 'Display a notification when the church livestream is currently broadcasting',
            }

  - label: 'Church Information'
    name: 'church'
    editor:
      preview: false
    files:
      - label: 'Contact Information'
        name: 'contact'
        file: 'content/church/contact.json'
        fields:
          - label: 'Phone Number'
            name: 'phone'
            widget: 'string'
            pattern: ['^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$', 'Must be a phone number']
            required: true
      - label: 'Service Times'
        name: 'service_times'
        file: 'content/church/service_times.json'
        fields:
          - label: 'Services'
            name: 'services'
            minimize_collapsed: true
            widget: 'list'
            hint: 'All church services and meetings throughout each week'
            fields:
              - label: 'Service'
                name: 'name'
                hint: 'Name of the service or meeting'
                widget: 'string'
                required: true
              - label: 'Day'
                name: 'day'
                widget: 'select'
                options: ['Sunday', 'Wednesday']
                required: true
              - label: 'Time'
                name: 'time'
                widget: 'string'
                required: true
                pattern: ['^[0-9]+\:[0-9]+[ap]m$', 'Must be a timestamp. Examples: 10:30am, 5:15pm']

  - label: 'Pages'
    name: 'pages'
    editor:
      preview: false
    files:
      - label: 'About Page'
        name: 'about'
        file: 'content/pages/about.json'
        fields:
          - label: 'Featured Image'
            name: 'hero_image'
            widget: 'image'
          - label: '"Our Mission" Image'
            name: 'mission_image'
            widget: 'image'
          - label: '"Why should I attend this Sunday?" Image'
            name: 'attend_image'
            widget: 'image'
          - label: 'Last Image'
            name: 'last_image'
            widget: 'image'

      - label: 'Beliefs Page'
        name: 'beliefs'
        file: 'content/pages/beliefs.json'
        fields:
          - { label: Description, name: description, widget: text }
          - { label: 'Featured Image', name: hero_image, widget: image }
          - label: 'Beliefs'
            name: 'belief_list'
            minimize_collapsed: true
            widget: 'list'
            fields:
              - { label: Belief Name, name: name, widget: string, required: true }
              - { label: Description, name: description, widget: string, required: true }
              - { label: Scripture References, name: references, widget: string }

      - label: "Children's Ministries Page"
        name: 'childrens_ministries'
        file: 'content/pages/childrens_ministries.json'
        fields:
          - { label: Description, name: description, widget: text }
          - { label: 'Featured Image', name: hero_image, widget: image }
          - label: 'Ministries'
            name: 'ministry_list'
            minimize_collapsed: true
            widget: 'list'
            fields: *MINISTRY

      - label: 'Contact Page'
        name: 'contact'
        file: 'content/pages/contact.json'
        fields:
          - { label: Description, name: description, widget: text }
          - { label: 'Featured Image', name: hero_image, widget: image }
          - label: 'Contacts'
            name: 'contact_list'
            minimize_collapsed: true
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string, required: true }
              - { label: Occupation, name: occupation, widget: string, required: true }
              - label: 'Email'
                name: 'email'
                widget: 'text'
                pattern: ['^[^\s@]+@[^\s@]+\.[^\s@]+$', 'Must be an email address']
                required: true

      - label: 'COVID-19 Page'
        name: 'covid'
        file: 'content/pages/covid.json'
        fields:
          - { label: Description, name: description, widget: text }
          - { label: 'Featured Image', name: hero_image, widget: image }

      - label: 'Events Page'
        name: 'events'
        file: 'content/pages/events.json'
        fields:
          - { label: Description, name: description, widget: text }
          - { label: 'Featured Image', name: hero_image, widget: image }
          - { label: "Ladies' Bible Study Featured Image", name: ladies_image, widget: image }
          - { label: "Ladies' Bible Study Description", name: ladies_description, widget: text }

      - label: 'Home Page'
        name: 'index'
        file: 'content/pages/index.json'
        fields:
          - { label: Title, name: title, widget: string, required: true }
          - { label: Description, name: description, widget: text, required: true }
          - { label: 'Featured Image', name: hero_image, widget: image, required: true }
          - {
              label: 'COVID-19 Section',
              name: covid,
              widget: boolean,
              default: true,
              hint: 'Display a notification about COVID-19 protocols',
            }
          - { label: 'COVID-19 Featured Image', name: covid_image, widget: image, required: true }

      - label: 'Give Page'
        name: 'give'
        file: 'content/pages/give.json'
        fields:
          - { label: Description, name: description, widget: text }
          - { label: 'Featured Image', name: hero_image, widget: image }

      - label: 'Leadership Page'
        name: 'leadership'
        file: 'content/pages/leadership.json'
        fields:
          - { label: Description, name: description, widget: text, required: true }
          - { label: 'Featured Image', name: hero_image, widget: image, required: true }
          - label: 'Leadership'
            name: 'leadership_list'
            minimize_collapsed: true
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string, required: true }
              - { label: Image, name: image, widget: image, required: true }
              - {
                  label: Occupation,
                  name: occupation,
                  widget: string,
                  required: true,
                  hint: 'Position within the church',
                }
              - { label: Description, name: description, widget: text, required: true }
              - label: 'Phone Number'
                name: 'phone'
                widget: 'string'
                pattern: ['^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$', 'Must be a phone number']
                required: true
              - label: 'Email'
                name: 'email'
                widget: 'text'
                pattern: ['^[^\s@]+@[^\s@]+\.[^\s@]+$', 'Must be an email address']
                required: true

      - label: 'Ministries Page'
        name: 'ministries'
        file: 'content/pages/ministries.json'
        fields:
          - { label: 'Featured Image', name: hero_image, widget: image, required: true }
          - label: 'Ministries'
            name: 'ministry_list'
            minimize_collapsed: true
            widget: 'list'
            fields: *MINISTRY

      - label: 'Missions Page'
        name: 'missions'
        file: 'content/pages/missions.json'
        fields:
          - { label: Description, name: description, widget: text, required: true }
          - { label: 'Featured Image', name: hero_image, widget: image, required: true }
          - label: 'Home Missionaries'
            hint: 'Missionaries directly supported by Northside'
            name: 'home_list'
            minimize_collapsed: true
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string, required: true }
              - { label: Location, name: location, widget: string, required: true }
          - label: 'Ministries'
            name: 'ministry_list'
            hint: 'Other missions-based ministries'
            minimize_collapsed: true
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string, required: true }
              - { label: Description, name: description, widget: string, required: true }
          - label: 'Missionaries (by Location)'
            name: 'country_list'
            minimize_collapsed: true
            widget: 'list'
            hint: 'List of supported missionaries, sorted by location/country they are serving in'
            fields:
              - { label: Location, name: name, widget: string, required: true }
              - label: 'Missionaries'
                name: 'missionary_list'
                widget: 'list'
                required: true
                fields:
                  - { label: Name, name: name, widget: string, required: true, hint: 'Missionary name' }

      - label: 'Sunday School Page'
        name: 'sunday_school'
        file: 'content/pages/sunday_school.json'
        fields:
          - { label: Description, name: description, widget: text, required: true }
          - { label: 'Featured Image', name: hero_image, widget: image, required: true }
          - label: 'Children Classes'
            name: 'children_class_list'
            minimize_collapsed: true
            widget: 'list'
            fields:
              - { label: 'Name / Age Group', name: name, widget: string, required: true }
              - { label: Room, name: room, widget: string, required: true }
          - label: 'Teen Classes'
            name: 'teen_class_list'
            minimize_collapsed: true
            widget: 'list'
            fields:
              - { label: 'Name / Age Group', name: name, widget: string, required: true }
              - { label: Room, name: room, widget: string, required: true }
          - label: 'Adults Classes'
            name: 'adult_class_list'
            minimize_collapsed: true
            widget: 'list'
            fields:
              - { label: 'Name / Age Group', name: name, widget: string, required: true }
              - { label: Room, name: room, widget: string, required: true }
          - label: 'Senior Citizen Classes'
            name: 'senior_citizen_class_list'
            minimize_collapsed: true
            widget: 'list'
            fields:
              - { label: 'Name / Age Group', name: name, widget: string, required: true }
              - { label: Room, name: room, widget: string, required: true }

      - label: 'Youth Ministries Page'
        name: 'youth_ministries'
        file: 'content/pages/youth_ministries.json'
        fields:
          - { label: Description, name: description, widget: text, required: true }
          - { label: 'Featured Image', name: hero_image, widget: image, required: true }
          - label: 'Ministries'
            name: 'ministry_list'
            minimize_collapsed: true
            widget: 'list'
            fields: *MINISTRY

  - label: 'Developer Settings'
    name: 'dev'
    description: 'Website configuration options for the client and server, only to be used by the developer.'
    editor:
      preview: false
    files:
      - label: 'Mapbox'
        name: mapbox
        description: 'Mapbox API settings.'
        summary: 'Mapbox API settings. This should not have to be edited.'
        file: 'content/dev/mapbox.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: 'Access Token', name: access_token, widget: string, hint: 'Mapbox API public token' }
          - label: 'Map Style'
            name: map_style
            widget: select
            options:
              - { label: 'Streets', value: 'streets-v11' }
              - { label: 'Outdoors', value: 'outdoors-v11' }
              - { label: 'Light', value: 'light-v10' }
              - { label: 'Dark', value: 'dark-v10' }
              - { label: 'Satellite', value: 'satellite-v9' }
              - { label: 'Navigation Day', value: 'navigation-day-v1' }
              - { label: 'Navigation Night', value: 'navigation-night-v1' }
            hint: 'Mapbox map style'
          - { label: 'Longitude', name: long, widget: number }
          - { label: 'Latitude', name: lat, widget: number }
